version: "3.7"
services:
  app:
    build:
      args:
        user: atis
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: survey_app
    container_name: survey_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - survey_net

  db:
    image: mysql:8.0
    container_name: survey_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "127.0.0.1:33060:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - survey_net

  nginx:
    image: nginx:1.17-alpine
    container_name: survey_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - survey_net

networks:
  survey_net:
    driver: bridge

